name 'WebServer'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures WebServer'
long_description 'Installs/Configures WebServer'
version '0.1.0'
